-- 0008_forum.sql — community forum (milestone 9, "Forum" section).
--
-- The webapp gains a Discourse-styled discussion forum at /forum. Anyone —
-- signed in or not — can read every category, topic and reply. Creating a
-- topic or posting a reply requires a signed-in account; any role qualifies
-- (public_user and up), there is no backoffice gate. Categories are curated
-- placeholder sections seeded here; there is no in-app category CRUD yet.
--
-- Write model — the webapp has NO service-role client, so every write goes
-- through the cookie-bound anon client under RLS:
--   * forum_topics / forum_posts get an INSERT policy for `authenticated`
--     scoped to `author_id = auth.uid()` — the same owner-scoped shape as
--     0006 (chat_sessions).
--   * `author_id` and the denormalised `author_name` are stamped by a
--     BEFORE-INSERT SECURITY DEFINER trigger, not trusted from the client
--     (profiles RLS only exposes a user's own row, so other authors' display
--     names are not otherwise readable via the anon client).
--   * `post_number` is assigned by a BEFORE-INSERT trigger; the client never
--     sends it.
--   * The denormalised counters on forum_topics (`reply_count`,
--     `last_posted_at`, `view_count`) are maintained by SECURITY DEFINER
--     triggers / functions — there is deliberately NO UPDATE policy on
--     forum_topics, mirroring the 0005 kill-switch approach.
--   * Creating a topic goes through `beleth_forum_create_topic(...)` so the
--     topic row and its first post land in one transaction.
--   * `beleth_forum_bump_view(...)` is granted to anon too, so logged-out
--     reads count like a real Discourse. Trivial counter inflation is
--     possible and accepted for a hackathon forum.
--
-- The agent (service role) never touches these tables; it bypasses RLS anyway.
--
-- Idempotent: safe to re-run. Applied by hand: Supabase dashboard -> SQL
-- Editor -> paste -> Run, or `uv run python scripts/apply_migration.py
-- db/migrations/0008_forum.sql`.

-- ── 1. categories ──────────────────────────────────────────────────────────
-- Curated sections. `color` is the hex used for the Discourse-style 6px left
-- border and the square badge. Seeded below; no write policy (service role /
-- migration only).
create table if not exists public.forum_categories (
    id          uuid        primary key default gen_random_uuid(),
    slug        text        not null unique,
    name        text        not null,
    description text            null,
    color       text        not null default '#d9a03c',
    position    integer     not null default 0,        -- ascending sort on the landing page
    created_at  timestamptz not null default now()
);

alter table public.forum_categories enable row level security;

drop policy if exists "anyone reads forum categories" on public.forum_categories;
create policy "anyone reads forum categories"
    on public.forum_categories
    for select
    to anon, authenticated
    using (true);

-- ── 2. topics ──────────────────────────────────────────────────────────────
-- One row per thread. `slug` is generated by beleth_forum_create_topic() as
-- <slugified-title>-<6 hex of the id> and is the URL key (/forum/t/<slug>).
-- The counters are denormalised for the topic-list columns and kept current
-- by the triggers/functions below, never by a direct client UPDATE.
create table if not exists public.forum_topics (
    id             uuid        primary key default gen_random_uuid(),
    category_id    uuid        not null references public.forum_categories (id) on delete cascade,
    slug           text        not null unique,
    title          text        not null,
    author_id      uuid        not null references auth.users (id) on delete cascade,
    author_name    text        not null default '',    -- denormalised display name, trigger-stamped
    created_at     timestamptz not null default now(),
    last_posted_at timestamptz not null default now(), -- topic-list "Activity" column; Latest ordering
    reply_count    integer     not null default 0,     -- posts after the original (post_number > 1)
    view_count     integer     not null default 0
);

create index if not exists idx_forum_topics_category_activity
    on public.forum_topics (category_id, last_posted_at desc);
create index if not exists idx_forum_topics_activity
    on public.forum_topics (last_posted_at desc);
create index if not exists idx_forum_topics_author
    on public.forum_topics (author_id);

alter table public.forum_topics enable row level security;

drop policy if exists "anyone reads forum topics" on public.forum_topics;
create policy "anyone reads forum topics"
    on public.forum_topics
    for select
    to anon, authenticated
    using (true);

-- Normal creation is via beleth_forum_create_topic(); a direct insert stays
-- safe because author_id is pinned to the caller (the trigger stamps it).
drop policy if exists "authenticated create forum topics" on public.forum_topics;
create policy "authenticated create forum topics"
    on public.forum_topics
    for insert
    to authenticated
    with check (author_id = (select auth.uid()));

-- ── 3. posts ───────────────────────────────────────────────────────────────
-- One row per message in a thread. post_number 1 is the original post;
-- replies are 2, 3, … assigned by trigger. `body` is plain text (the webapp
-- renders it with white-space:pre-wrap, like the chat feature — no markdown).
create table if not exists public.forum_posts (
    id          uuid        primary key default gen_random_uuid(),
    topic_id    uuid        not null references public.forum_topics (id) on delete cascade,
    author_id   uuid        not null references auth.users (id) on delete cascade,
    author_name text        not null default '',       -- denormalised display name, trigger-stamped
    body        text        not null,
    post_number integer     not null default 1,        -- trigger-assigned; 1 = original post
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

create index if not exists idx_forum_posts_topic
    on public.forum_posts (topic_id, post_number);
create index if not exists idx_forum_posts_author
    on public.forum_posts (author_id);

drop trigger if exists trg_forum_posts_touch_updated_at on public.forum_posts;
create trigger trg_forum_posts_touch_updated_at
    before update on public.forum_posts
    for each row execute function public.beleth_touch_updated_at();

alter table public.forum_posts enable row level security;

drop policy if exists "anyone reads forum posts" on public.forum_posts;
create policy "anyone reads forum posts"
    on public.forum_posts
    for select
    to anon, authenticated
    using (true);

drop policy if exists "authenticated create forum posts" on public.forum_posts;
create policy "authenticated create forum posts"
    on public.forum_posts
    for insert
    to authenticated
    with check (
        author_id = (select auth.uid())
        and exists (select 1 from public.forum_topics t where t.id = topic_id)
    );

-- ── 4. author / post-number stamping ───────────────────────────────────────
-- SECURITY DEFINER: pins author_id to the caller and fills author_name from
-- auth.users regardless of the caller's RLS view. Runs BEFORE the RLS
-- with-check, so `author_id = auth.uid()` still holds for a client insert
-- that omits the column.
create or replace function public.beleth_forum_stamp_author()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.author_id := (select auth.uid());
  new.author_name := coalesce(
    split_part((select email from auth.users where id = new.author_id), '@', 1),
    'someone'
  );
  return new;
end;
$$;

drop trigger if exists trg_forum_topics_stamp_author on public.forum_topics;
create trigger trg_forum_topics_stamp_author
    before insert on public.forum_topics
    for each row execute function public.beleth_forum_stamp_author();

drop trigger if exists trg_forum_posts_stamp_author on public.forum_posts;
create trigger trg_forum_posts_stamp_author
    before insert on public.forum_posts
    for each row execute function public.beleth_forum_stamp_author();

-- Assigns the next post_number within the topic. The client never sends it.
create or replace function public.beleth_forum_set_post_number()
returns trigger
language plpgsql
as $$
begin
  select coalesce(max(post_number), 0) + 1
    into new.post_number
    from public.forum_posts
   where topic_id = new.topic_id;
  return new;
end;
$$;

drop trigger if exists trg_forum_posts_set_post_number on public.forum_posts;
create trigger trg_forum_posts_set_post_number
    before insert on public.forum_posts
    for each row execute function public.beleth_forum_set_post_number();

-- ── 5. counter maintenance ─────────────────────────────────────────────────
-- After a post lands, move the topic's activity timestamp and (for replies,
-- not the original post) bump reply_count. SECURITY DEFINER so it can update
-- forum_topics with no UPDATE policy in play.
create or replace function public.beleth_forum_after_post_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.forum_topics
     set last_posted_at = new.created_at,
         reply_count = reply_count + (case when new.post_number = 1 then 0 else 1 end)
   where id = new.topic_id;
  return null;
end;
$$;

drop trigger if exists trg_forum_posts_after_insert on public.forum_posts;
create trigger trg_forum_posts_after_insert
    after insert on public.forum_posts
    for each row execute function public.beleth_forum_after_post_insert();

-- ── 6. create a topic (atomic: topic + first post) ─────────────────────────
-- Raises 42501 if not signed in, 22023 on a bad title/body, 23503 on an
-- unknown category. Returns the fresh topic row so the caller can redirect to
-- /forum/t/<slug> without a re-read. author_id / author_name / post_number
-- are filled by the triggers above.
create or replace function public.beleth_forum_create_topic(
    p_category_id uuid,
    p_title       text,
    p_body        text
)
returns public.forum_topics
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid   uuid := (select auth.uid());
  v_id    uuid := gen_random_uuid();
  v_base  text;
  v_slug  text;
  v_topic public.forum_topics;
begin
  if v_uid is null then
    raise exception 'must be signed in to create a topic' using errcode = '42501';
  end if;
  if p_title is null or char_length(btrim(p_title)) < 3 or char_length(p_title) > 120 then
    raise exception 'title must be 3 to 120 characters' using errcode = '22023';
  end if;
  if p_body is null or char_length(btrim(p_body)) < 1 or char_length(p_body) > 8000 then
    raise exception 'body must be 1 to 8000 characters' using errcode = '22023';
  end if;
  if not exists (select 1 from public.forum_categories where id = p_category_id) then
    raise exception 'unknown category' using errcode = '23503';
  end if;

  v_base := lower(regexp_replace(btrim(p_title), '[^a-zA-Z0-9]+', '-', 'g'));
  v_base := btrim(v_base, '-');
  if v_base = '' then
    v_base := 'topic';
  end if;
  v_slug := left(v_base, 60) || '-' || substr(v_id::text, 1, 6);

  insert into public.forum_topics (id, category_id, slug, title, author_id, last_posted_at)
  values (v_id, p_category_id, v_slug, btrim(p_title), v_uid, now())
  returning * into v_topic;

  insert into public.forum_posts (topic_id, author_id, body)
  values (v_id, v_uid, btrim(p_body));

  return v_topic;
end;
$$;

revoke all on function public.beleth_forum_create_topic(uuid, text, text) from public, anon;
grant execute on function public.beleth_forum_create_topic(uuid, text, text) to authenticated;

-- ── 7. view counter ────────────────────────────────────────────────────────
-- Called once per topic open by a small client component. Granted to anon so
-- logged-out reads count too (Discourse behaviour).
create or replace function public.beleth_forum_bump_view(p_topic_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.forum_topics
     set view_count = view_count + 1
   where id = p_topic_id;
end;
$$;

revoke all on function public.beleth_forum_bump_view(uuid) from public;
grant execute on function public.beleth_forum_bump_view(uuid) to anon, authenticated;

-- ── 8. seed categories ─────────────────────────────────────────────────────
insert into public.forum_categories (slug, name, description, color, position) values
    ('announcements', 'Announcements',
     'Release notes and status updates from the Beleth team.',            '#d9a03c', 1),
    ('strategy',      'Strategy & Signals',
     'The volatility-risk-premium approach, the DTE ladder, the exit rules — discuss how Beleth decides.', '#35a67c', 2),
    ('feedback',      'Site Feedback',
     'Bugs, rough edges and ideas for the dashboard and this forum.',     '#5b8fb0', 3),
    ('general',       'General',
     'Anything else about options, paper trading and autonomous agents.', '#8c959d', 4)
on conflict (slug) do nothing;
